import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ThemeProvider } from "../components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dallet",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      {/* <ThemeProvider */}
      {/*   attribute="class" */}
      {/*   defaultTheme="system" */}
      {/*   enableSystem */}
      {/*   disableTransitionOnChange */}
      {/* > */}
      <body className={inter.className}>{children}</body>
      {/* </ThemeProvider> */}
    </html>
  );
}
