import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Appbar from "@repo/ui/components/Appbar";
import Authbtn from "~/components/Authbtn";
import Provider from "~/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dallet",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${inter.className}`} >
        <Provider>
          <Appbar children={<Authbtn />} />
          <div className="mx-5" >
            {children}
          </div>
        </Provider>
      </body>

    </html>
  );
}
