import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/globals.css";
import Appbar from "@repo/ui/components/Appbar";
import Provider from '../components/providers';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wallet adapter example",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${inter.className}`} >
        <Provider >
          <Appbar children={<></>} />
          {children}
        </Provider>
      </body>
    </html>
  );
}

